// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkHp7E94hk6yQin9JkrV5hrl0Q76ezws',
    appId: '1:818638821075:web:a40f28a142fa730d1c6626',
    messagingSenderId: '818638821075',
    projectId: 'fir-wisy',
    authDomain: 'fir-wisy.firebaseapp.com',
    storageBucket: 'fir-wisy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7wyQYW884gSgTnIaqj0hyzWoSGrBwKjg',
    appId: '1:818638821075:android:c7d960afd54337891c6626',
    messagingSenderId: '818638821075',
    projectId: 'fir-wisy',
    storageBucket: 'fir-wisy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRUW8Cx5yjBYoHrUrk9E95JYkn24ZIaUg',
    appId: '1:818638821075:ios:18e3bf92f1fd82121c6626',
    messagingSenderId: '818638821075',
    projectId: 'fir-wisy',
    storageBucket: 'fir-wisy.appspot.com',
    iosBundleId: 'com.example.applicationWisy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRUW8Cx5yjBYoHrUrk9E95JYkn24ZIaUg',
    appId: '1:818638821075:ios:18e3bf92f1fd82121c6626',
    messagingSenderId: '818638821075',
    projectId: 'fir-wisy',
    storageBucket: 'fir-wisy.appspot.com',
    iosBundleId: 'com.example.applicationWisy',
  );
}
